version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network
    ports: [42333:3306]

  wordpress:
    depends_on:
      - db
    image: php:7.2-fpm
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ./project/:/var/www/html
      - ./php/conf.d/:/usr/local/etc/php/conf.d
    # command: "docker-php-ext-install mysqli && docker-php-ext-enable mysqli"
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./project/:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  dbdata:
  project:
  nginx-conf:

networks:
  app-network:
    driver: bridge
